default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_development
  username: postgres
  password: jesus1989

test:
  <<: *default
  database: hellorails_test
  username: postgres
  password: jesus1989

production:
  <<: *default
  database: hellorails_production
  username: postgres
  password: jesus1989
